update `PackageInfo` and `ProjectInfo` docs
JuliaLang/Pkg.jl pull request #3149
Opened 2022-07-29 14:20 UTC by t-bltg

Some field descriptions were missing.

2022-10-01 14:01 UTC, t-bltg commented
@IanButterworth, can this harmless PR be merged ?

2022-10-24 22:02 UTC, IanButterworth requested changes

2022-10-24 22:02 UTC, IanButterworth commented on src/Pkg.jl
> +| `version`             | The version of the package (this is `Nothing` for stdlibs)                        |
```suggestion
| `version`             | The version of the package (this is `Nothing` for stdlibs)                        |
| `tree_hash`           | A file hash of the package directory tree                                         |
```

2022-10-24 22:02 UTC, IanButterworth commented on src/Pkg.jl
> +| `version`             | The version of the package (this is `Nothing` for stdlibs)                        |
Or was this omitted for a reason?

2022-10-25 16:21 UTC, t-bltg commented on src/Pkg.jl
> +| `version`             | The version of the package (this is `Nothing` for stdlibs)                        |
I think I just missed it.

2022-11-04 15:57 UTC, IanButterworth approved these changes

2022-11-04 15:57 UTC, merged