fixup jll versions that are supposed to stay fixed during e.g Pkg.add
JuliaLang/Pkg.jl pull request #3371
Opened 2023-02-14 13:53 UTC by KristofferC

Alternative to https://github.com/JuliaLang/Pkg.jl/pull/3368. This is a bit of a more "surgical" fix to the issue of jlls getting updated from e.g. `Pkg.add` than trying to fully support build numbers in the resolver etc.

2023-02-14 14:03 UTC, IanButterworth commented
You call that a diff?

LGTM!

2023-02-14 19:27 UTC, DilumAluthge commented
Can we also backport this to earlier Julia versions, such as 1.6?

2023-02-14 20:12 UTC, KristofferC commented
Probably yes

2023-02-14 20:15 UTC, DilumAluthge approved these changes

2023-02-14 21:52 UTC, staticfloat approved these changes

2023-02-14 22:11 UTC, DilumAluthge reviewed
It occurs to me that if the resolver changes the major/minor/patch of a JLL, then we shouldn't do the fixup, right?

E.g. if the resolver changes `1.2.3+0` to `1.2.3+1`, then we should do the fixup - i.e. we should change it back to `1.2.3+0`.

But if the resolver changes `1.2.3+0` to `1.2.4+1`, then we shouldn't do the fixup - i.e. we should keep it as `1.2.4+1`.

Does that sound right?

2023-02-14 22:11 UTC, DilumAluthge commented on src/Operations.jl
> +        if old_v !== nothing
```suggestion
        # We only fixup a JLL if the old major/minor/patch matches the new major/minor/patch
        if old_v !== nothing && Base.thispatch(old_v) == Base.thispatch(vers_fix[uuid])
```

2023-02-14 22:27 UTC, KristofferC commented
> It occurs to me that if the resolver changes the major/minor/patch of a JLL, then we shouldn't do the fixup, right?

This should never happen though since we require that the package has the given version. So the only reason this code does anything is due to the build number stripping that happens when passing things into the resolver.

But we can be super defensive and check that anyway, yes.

2023-02-15 15:33 UTC, IanButterworth requested changes
Looks good, just needs tests

2023-02-20 17:38 UTC, IanButterworth commented on test/new.jl
> +    end
This isnt needed now. I'd just add and check in the test directly

2023-02-20 18:35 UTC, IanButterworth commented on test/new.jl
> +    @test Pkg.dependencies()[imjll_uuid].version == v"6.9.11+4"
I think this should be inside an isolate?

2023-02-21 03:09 UTC, IanButterworth approved these changes

2023-02-21 06:24 UTC, merged